import type { Metadata } from "next";
import { Geist, Geist_Mono, Bitter } from "next/font/google";
import "./globals.css";
import VLibrasClient from "@/components/shared/libras/Vlibras";
import { AccessibilityProvider } from "@/components/shared/accessibility/AccessibilityContext";
import AccessibilitySidebar from "@/components/shared/accessibility/AccessibilitySidebar";
import AccessibilityGlobalStyles from "@/components/shared/accessibility/AccessibilityGlobalStyles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bitterSerif = Bitter({
  variable: "--font-bitter-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bitterSerif.variable} antialiased`}
      >
        <AccessibilityProvider>
          <AccessibilityGlobalStyles />
          <AccessibilitySidebar />
          <VLibrasClient />
          {children}
        </AccessibilityProvider>
      </body>
    </html>
  );
}
